services:
  postgres:
    image: postgres:16-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: fintech-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: fintech
      RABBITMQ_DEFAULT_PASS: fintech
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: